---
title: "A Combinatorial Proof of Binet's Formula"
date: "2017-12-01T21:49:57-07:00"
categories:
  - Products
tags:
  - Combinatorics
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Binet's Formula

The Binet's formula is also known as the explicit expression of *n-th* term of the Fibbonacci Sequence. 


### Brief Introduction 
Counting is a very basic skill. We have all been learning how to count since we were very young. If we think back to our childhood, other than simple vocabulary like “daddy” and “mommy”, the most common thing was to count the numbers from one to ten. In this case, counting could be the first exposure to mathematics for many people. Now, we still count in daily life, such as money exchange, time management, fortune accumulation, etc. However, the beauty of counting is more than that. We can apply the concept of counting in various mathematical problems and proofs.

### Tools

I employed counting's principle, DIE method by modern mathematician Doron Zeiberger. Principles in combinatorics are pioneered by modern mathematician Benjamin and Quinn. Without all knowledge above, there is no such proof can be exsited. Contact for more information.


